name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  deploy:
    name: Deploy to Maven Central
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java and GPG
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
          server-id: ossrh
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Publish to Maven Central
        run: mvn --batch-mode -DperformRelease=true clean deploy
